/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fhxycqvssizeqgbbsgmt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoeHljcXZzc2l6ZXFnYmJzZ210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1MzI1MjIsImV4cCI6MjA5MzEwODUyMn0.-UlBwG0Rf72bQFyzbba6YeZJXc7wIg52wCE1-7GM5x0"